### ISSUE TITLE
Consider a stronger password hashing method

### ISSUE THREAD

**Issue by NicholasMiller** [aworley/ocm#3]
Well hello there!

While reviewing your code I noticed that your password encryption scheme is based on [MD5](https://github.com/aworley/ocm/blob/a5fc1ff19beec53ff226fdfd70400addbd33ecb4/cms/app/lib/pikaAuthDb.php#L107). Just wanted to bring to your attention that this is an incredibly insecure way to protect passwords due to the efficiency of the MD5 hashing algorithm. The speed at which strings can be hashed make brute force attacks quite easy to conduct. Hackers can literally compare hashes agains billions of combinations per second with a powerful GPU.

I would strongly suggest hashing your passwords with BCRYPT ([supported natively](http://php.net/manual/en/function.password-hash.php) in PHP as of v5.5.0).

Have a good one! 
Nick

**Comment by aworley** [comment]
Hi Nick, thanks for chiming in with your thoughts.  The CMS does actually use BCRYPT/password_hash if it's available on the host server.  It falls back to MD5 otherwise - there are many users still on PHP 5.1 who need this left in.  You can review this feature here:  https://github.com/aworley/ocm/commit/f8f8929afbe4403703aafe3de115a7f8fcc3020f

Best,
Aaron

**Comment by NicholasMiller** [comment]
👍 

Whoops! Sorry, totally missed that. Just saw the md5 bit and figured bcrypt had been overlooked.
